#!/usr/bin/env python3

import os
setup_path = os.path.join(os.path.dirname(
  os.path.abspath(__file__)),
  'setup.py',
)
version_path = os.path.join(os.path.dirname(
  os.path.abspath(__file__)),
  'VERSION',
)
version = '0.0.0'
with open(version_path, 'r') as vh:
    version = vh.read()

version = version.split('.')
version[-1] = str(int(version[-1]) + 1)

version = '.'.join(version)

with open(version_path, 'w') as vh:
    vh.write(version)

if not os.system('python {} sdist upload -r pypi'.format(setup_path)):
    print ("Uploaded to PyPI as Version {}. Don't forget to tag!".format(version))